spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/mealio
    username: mealio
    password: mealio
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  flyway:
    enabled: true
    schemas: menu_schema
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health

server:
  port: 8080